# Site settings
title: 4pFoods Asset Hub
email: dev@ocupop.com
url: "https://assets.4pfoods.com"
permalink: pretty

# Social sharing
description:
socialshare:
  featured_image: img/socialshare.png
  twitter:
    username:
    image:

# Google Analytics
analytics_code:


# Collections
collections:
  pages:
    output: true

defaults:
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Build settings
safe: false
sass:
  # style: compressed
  sass_dir: _scss
plugins:
  - jekyll-sitemap

placeholder_image: https://via.placeholder.com/1000x1000/333333/000000?text=Placeholder